version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
####### add a bind mount ##########################
#Agar tidak me rebuild docker compose (docker-compose up) ketika melakukan edit pada aplikasi kita (app.py)
    volumes:
        - .:/code
    environment:
        FLASK_ENV: development
####################################################
  redis:
    image: "redis:alpine"

#This Compose file defines two services: web and redis.